version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: container_integrador
    volumes:
      - ./postgres:/var/lib/postgresql/data
